### PR TITLE
Update dependencies and deployment target

### PR DESCRIPTION
**Pull request by jiayi-zhou**
Update to AccessibilitySnapshot 0.4.1 and Playbook 0.2.1 and update deployment target of example project to 14.2

### CODE REVIEW

**Review by ra1028 — APPROVED** [review]
Thanks @jiayi-zhou 

If you want to publish a new version to the cocoapods, add a new tag, and write a release on GitHub, and then the new version will be published automatically by github-actions.

**Comment by ra1028** [comment]
@jiayi-zhou 
Ah sorry, looks CI was failed. I guess there are diffs after running format.
Please fix it, then if the CI is passed, you can merge this yorself.

**Comment by jiayi-zhou** [comment]
I ran this command locally and it seems to pass. I think this may be an issue with either our CI setup or a temporary issue with Github action itself (could be related to this: https://github.com/actions/virtual-environments/issues/2247). I tried with a new PR: #12, and it fails here also. Should I merge this for now?

**Comment by ra1028** [comment]
@jiayi-zhou
Okay, then let's merge this for now. and revisit this after the maintenance :)

**Pull request merged**
